{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Mutiple Cycles Log files\",\"Log_File_Selection_Parameter\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1203.0 (24.11)"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Log_File_Selection_Parameter",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Use this parameter to select the log file you want to display on the dashboard.",
        "expression": "\"execution_log_oracle_peoplesoft_multiple_cycles.csv\" meta [IsParameterQuery=true, List={\"LMS_CMSDM_Logs_3_Cycles.csv\", \"LMS_CLMDM_Logs_3_Cycles.csv\", \"execution_log_azure_mssql.csv\", \"execution_log_oracle_peoplesoft_multiple_cycles.csv\", \"LMS_LMSDM_Logs_3_Cycles.csv\", \"abcd\"}, DefaultValue=\"LMS_LMSDM_Logs_3_Cycles.csv\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d795dd46-a9e7-4d39-9032-c4306e494c12"
      }
    ],
    "relationships": [
      {
        "name": "ccaa9f26-9d44-4ddd-aca3-9608b8990ce5",
        "fromColumn": "start_time",
        "fromTable": "Mutiple Cycles Log files",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b5a9976b-9ba0-4bbc-b316-c55df0082f3f"
      },
      {
        "name": "3c571d51-32c6-4311-9b73-ffe1ff8e88e8",
        "fromColumn": "end_time",
        "fromTable": "Mutiple Cycles Log files",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2fe93df6-7a6b-49d2-a6f1-ec231cae8eda"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_d7a9fb50-26e2-4224-8cec-420b2ff3f0f4",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e5db4df6-3d7d-40be-93e1-ad9a986fea63",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f3f6f7dc-6244-427b-9f83-a204e8d03d36",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0d5f6e1c-830b-4618-899e-f3472f0cea6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8a69307d-fc6b-4f11-8e48-a75cb07556e8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b5234869-ea34-4b36-a782-d02ba0e5f480",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "513303a4-d312-4ee0-8062-36c4c81b4d58",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4beaa8e4-8efa-4d63-9448-2e0647c6f8c2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "001c51e7-57bc-4a7f-85db-10e7f59bb60a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "11c60c38-2ea8-47f4-b1c6-57c369ffbea0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "484e2a64-e22f-408e-8537-97d669a693a0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e713bf00-7e9a-4040-8f87-9e587ce7755b",
                "ordinal": 3
              }
            ],
            "lineageTag": "5ca601dd-caa8-49f7-957b-0912016995cc"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "bede1e6f-d16f-49eb-95b2-85090363ead8",
        "partitions": [
          {
            "name": "DateTableTemplate_d7a9fb50-26e2-4224-8cec-420b2ff3f0f4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Mutiple Cycles Log files",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "schema",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dc380e1-2b17-4c68-8103-807f508682d5",
            "sourceColumn": "schema",
            "summarizeBy": "none"
          },
          {
            "name": "table",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c2f9e41-c10f-4415-87d7-7d8d7cc2d689",
            "sourceColumn": "table",
            "summarizeBy": "none"
          },
          {
            "name": "row_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d62ec973-c647-4585-a47c-bbceb3494541",
            "sourceColumn": "row_count",
            "summarizeBy": "sum"
          },
          {
            "name": "distinct_row_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "beafae82-abf9-4d25-b10f-d8a122c675c2",
            "sourceColumn": "distinct_row_count",
            "summarizeBy": "sum"
          },
          {
            "name": "column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1b81209-85ee-42b3-a3ba-94458d3c1899",
            "sourceColumn": "column",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c058dd30-8457-4cac-8bcf-4e20b3cfb8ca",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "start_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c6f91b59-2cfb-404b-a1fc-f4e3311acb86",
            "sourceColumn": "start_time",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b5a9976b-9ba0-4bbc-b316-c55df0082f3f"
                },
                "isDefault": true,
                "relationship": "ccaa9f26-9d44-4ddd-aca3-9608b8990ce5"
              }
            ]
          },
          {
            "name": "end_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "20c44246-df02-4cea-940d-094724167ed4",
            "sourceColumn": "end_time",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2fe93df6-7a6b-49d2-a6f1-ec231cae8eda"
                },
                "isDefault": true,
                "relationship": "3c571d51-32c6-4311-9b73-ffe1ff8e88e8"
              }
            ]
          },
          {
            "name": "duration(s)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "e26b7da8-45cd-4a05-bf8a-55b760c6bc1a",
            "sourceColumn": "duration(s)",
            "summarizeBy": "sum"
          },
          {
            "name": "duration(min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "37886e26-b787-4faa-8f75-96e7873a8f7d",
            "sourceColumn": "duration(min)",
            "summarizeBy": "sum"
          },
          {
            "name": "cycle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "664e4c55-49d9-42d2-b50a-1d28852e5ff5",
            "sourceColumn": "cycle",
            "summarizeBy": "sum"
          },
          {
            "name": "error",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85eec02a-b387-4d71-a22a-3cd33dec527e",
            "sourceColumn": "error",
            "summarizeBy": "none"
          },
          {
            "name": "line_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d5a17a3-b6b6-4402-834e-008369234d27",
            "sourceColumn": "line_number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4c1329a2-75f7-454e-96e4-67f8320ee1a0",
        "partitions": [
          {
            "name": "Mutiple Cycles Log files",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\NitiPatel\\Desktop\\Documents\\tdm_log_analytics\\tdm_log_analytics\\execution_results\"),",
                "    #\"C:\\Users\\NitiPatel\\Desktop\\Documents\\tdm_log_analytics\\tdm_log_analytics\\execution_results\\_LMS_CLMDM_Logs_3_Cycles csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\NitiPatel\\Desktop\\Documents\\tdm_log_analytics\\tdm_log_analytics\\execution_results\\\",Name=Log_File_Selection_Parameter]}[Content],",
                "    #\"Imported CSV\" = Csv.Document(#\"C:\\Users\\NitiPatel\\Desktop\\Documents\\tdm_log_analytics\\tdm_log_analytics\\execution_results\\_LMS_CLMDM_Logs_3_Cycles csv\",[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Imported CSV\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"cycle\", Int64.Type}, {\"schema\", type text}, {\"table\", type text}, {\"row_count\", Int64.Type}, {\"distinct_row_count\", Int64.Type}, {\"column\", type text}, {\"status\", type text}, {\"start_time\", type datetime}, {\"end_time\", type datetime}, {\"duration(s)\", Int64.Type}, {\"duration(min)\", type number}, {\"error\", type text}, {\"line_number\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_b5a9976b-9ba0-4bbc-b316-c55df0082f3f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2a41b207-05c8-492f-9eda-0834cecca755",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "8c1abc24-2080-44a7-a223-b7ac1ae591c8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9a7e7e7d-a1ab-45c7-906d-04c103131eb7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ad3ae629-25b1-40fa-84d3-bab279251e99",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7dc7c636-d2e2-413a-901d-1bbb665f2bf5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "055fe82d-2b56-49a5-a6c1-e874bbed79e3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1c8b2c1e-d9a7-470e-aa98-c6e1ce583969",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "eeeedfaf-2062-48c9-b39a-746aa3cd5057",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "92146fcc-427c-48f5-b0d3-271c7d046670",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "958a9ca9-8a3e-48e5-acaa-50e5be2d107a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6dde1ca3-1b09-42f7-8017-cfb7c690ef8d",
                "ordinal": 3
              }
            ],
            "lineageTag": "97443c7e-49c6-4b88-a1b2-763b02072e60"
          }
        ],
        "isHidden": true,
        "lineageTag": "05dcd289-ba9a-4d83-b852-9b7e3ab4df3d",
        "partitions": [
          {
            "name": "LocalDateTable_b5a9976b-9ba0-4bbc-b316-c55df0082f3f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Mutiple Cycles Log files'[start_time])), 1, 1), Date(Year(MAX('Mutiple Cycles Log files'[start_time])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2fe93df6-7a6b-49d2-a6f1-ec231cae8eda",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fd8fa63e-af86-4671-a693-4099fb862c53",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "124d6262-839f-4340-827b-239e48f7a5df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "fe970b48-a6e5-493d-b354-199543e4881d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a48056a1-f1b2-446c-aec3-bdceb3c5a013",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7624a86d-1c7a-44d8-a396-a1d6532ee93d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f499701e-35e5-4cdf-88f7-e2b5269c7971",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d670eba7-f04d-45e2-a7ed-bda1bd102f98",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "03e913b4-bc63-4975-a787-914c7f612fd4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "db69aa19-b3a3-4980-b9fe-56cdd000da7e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a347ccf4-c906-4876-a21a-f5c495a34b22",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f7018fb9-1a8f-494a-98c5-c06c9d5bfca2",
                "ordinal": 3
              }
            ],
            "lineageTag": "42c98d97-1b30-43f0-bf15-eabd678ba740"
          }
        ],
        "isHidden": true,
        "lineageTag": "93b088a2-ec7b-4596-acff-76bd01364f6f",
        "partitions": [
          {
            "name": "LocalDateTable_2fe93df6-7a6b-49d2-a6f1-ec231cae8eda",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Mutiple Cycles Log files'[end_time])), 1, 1), Date(Year(MAX('Mutiple Cycles Log files'[end_time])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}